spring:
  application:
    name: test
  grpc:
    client:
      channel:
        person-service:
          target: static://localhost:9090
      channelfactory:
        enabled: true
    server:
      port: 9090
      address: localhost
